// Global skill catalogue (SPEC §4). Aliases cover the spellings found in CVs and job descriptions; matching is
// case- and punctuation-insensitive (src/lib/skills/normalize.ts). Resources are hand-picked official docs or
// well-known free courses; the AI never generates learning links.
//
// Effort: 1 small (days), 2 medium (weeks), 3 large (months), as a rough guide for learning priorities.

export type SkillSeed = {
  slug: string;
  name: string;
  category: string;
  aliases?: string[];
  effort?: 1 | 2 | 3;
  resources?: { title: string; url: string }[];
};

const doc = (title: string, url: string) => [{ title, url }];

export const SKILLS: SkillSeed[] = [
  // Languages
  {
    slug: "javascript",
    name: "JavaScript",
    category: "language",
    aliases: ["JS", "ECMAScript", "ES6", "ES2015", "Vanilla JS"],
    effort: 3,
    resources: doc("MDN JavaScript Guide", "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide"),
  },
  {
    slug: "typescript",
    name: "TypeScript",
    category: "language",
    aliases: ["TS"],
    effort: 2,
    resources: doc("TypeScript Handbook", "https://www.typescriptlang.org/docs/handbook/intro.html"),
  },
  {
    slug: "html",
    name: "HTML",
    category: "language",
    aliases: ["HTML5", "Semantic HTML"],
    effort: 1,
    resources: doc("MDN HTML", "https://developer.mozilla.org/en-US/docs/Web/HTML"),
  },
  {
    slug: "css",
    name: "CSS",
    category: "language",
    aliases: ["CSS3", "Flexbox", "CSS Grid"],
    effort: 2,
    resources: doc("MDN CSS", "https://developer.mozilla.org/en-US/docs/Web/CSS"),
  },
  {
    slug: "python",
    name: "Python",
    category: "language",
    effort: 2,
    resources: doc("The Python Tutorial", "https://docs.python.org/3/tutorial/"),
  },
  {
    slug: "java",
    name: "Java",
    category: "language",
    effort: 3,
    resources: doc("Learn Java (dev.java)", "https://dev.java/learn/"),
  },
  {
    slug: "go",
    name: "Go",
    category: "language",
    aliases: ["Golang"],
    effort: 2,
    resources: doc("A Tour of Go", "https://go.dev/tour/"),
  },
  { slug: "csharp", name: "C#", category: "language", aliases: ["C Sharp", "CSharp"], effort: 3 },
  { slug: "kotlin", name: "Kotlin", category: "language", effort: 2 },
  { slug: "swift", name: "Swift", category: "language", effort: 2 },
  { slug: "dart", name: "Dart", category: "language", effort: 2 },
  { slug: "sql", name: "SQL", category: "language", aliases: ["Structured Query Language"], effort: 2 },
  { slug: "php", name: "PHP", category: "language", effort: 2 },
  { slug: "ruby", name: "Ruby", category: "language", effort: 2 },
  { slug: "rust", name: "Rust", category: "language", effort: 3 },
  { slug: "cpp", name: "C++", category: "language", aliases: ["CPP"], effort: 3 },

  // Frontend frameworks and libraries
  {
    slug: "react",
    name: "React",
    category: "framework",
    aliases: ["React.js", "ReactJS", "React JS", "React Hooks"],
    effort: 2,
    resources: doc("react.dev: Learn React", "https://react.dev/learn"),
  },
  {
    slug: "nextjs",
    name: "Next.js",
    category: "framework",
    aliases: ["NextJS", "Next JS", "Next.js App Router"],
    effort: 2,
    resources: doc("Next.js Learn", "https://nextjs.org/learn"),
  },
  {
    slug: "vue",
    name: "Vue.js",
    category: "framework",
    aliases: ["Vue", "VueJS", "Vue 3"],
    effort: 2,
    resources: doc("Vue.js Guide", "https://vuejs.org/guide/introduction.html"),
  },
  { slug: "nuxt", name: "Nuxt", category: "framework", aliases: ["Nuxt.js", "NuxtJS"], effort: 2 },
  {
    slug: "angular",
    name: "Angular",
    category: "framework",
    aliases: ["Angular 2+", "Angular 17"],
    effort: 3,
    resources: doc("Angular tutorials", "https://angular.dev/tutorials"),
  },
  {
    slug: "svelte",
    name: "Svelte",
    category: "framework",
    effort: 2,
    resources: doc("Svelte tutorial", "https://svelte.dev/tutorial"),
  },
  { slug: "sveltekit", name: "SvelteKit", category: "framework", effort: 2 },
  { slug: "remix", name: "Remix", category: "framework", aliases: ["React Router 7"], effort: 2 },
  { slug: "astro", name: "Astro", category: "framework", effort: 1 },
  { slug: "gatsby", name: "Gatsby", category: "framework", aliases: ["GatsbyJS"], effort: 1 },
  { slug: "jquery", name: "jQuery", category: "library", effort: 1 },
  {
    slug: "redux",
    name: "Redux",
    category: "library",
    aliases: ["Redux.js"],
    effort: 2,
    resources: doc("Redux Essentials", "https://redux.js.org/tutorials/essentials/part-1-overview-concepts"),
  },
  { slug: "redux-toolkit", name: "Redux Toolkit", category: "library", aliases: ["RTK", "RTK Query"], effort: 1 },
  {
    slug: "zustand",
    name: "Zustand",
    category: "library",
    effort: 1,
    resources: doc("Zustand docs", "https://zustand.docs.pmnd.rs/"),
  },
  { slug: "mobx", name: "MobX", category: "library", effort: 1 },
  { slug: "recoil", name: "Recoil", category: "library", effort: 1 },
  { slug: "jotai", name: "Jotai", category: "library", effort: 1 },
  {
    slug: "tanstack-query",
    name: "TanStack Query",
    category: "library",
    aliases: ["React Query", "Tanstack React Query"],
    effort: 1,
    resources: doc("TanStack Query docs", "https://tanstack.com/query/latest/docs/framework/react/overview"),
  },
  { slug: "swr", name: "SWR", category: "library", effort: 1 },
  { slug: "react-router", name: "React Router", category: "library", aliases: ["React Router DOM"], effort: 1 },
  { slug: "react-hook-form", name: "React Hook Form", category: "library", aliases: ["RHF"], effort: 1 },
  { slug: "formik", name: "Formik", category: "library", effort: 1 },
  { slug: "zod", name: "Zod", category: "library", effort: 1 },
  { slug: "rxjs", name: "RxJS", category: "library", aliases: ["Reactive Extensions"], effort: 2 },
  { slug: "threejs", name: "Three.js", category: "library", aliases: ["ThreeJS", "React Three Fiber"], effort: 2 },
  { slug: "d3", name: "D3.js", category: "library", aliases: ["D3"], effort: 2 },
  { slug: "chartjs", name: "Chart.js", category: "library", aliases: ["ChartJS"], effort: 1 },
  { slug: "recharts", name: "Recharts", category: "library", effort: 1 },
  { slug: "framer-motion", name: "Framer Motion", category: "library", aliases: ["Motion"], effort: 1 },

  // Styling and UI kits
  {
    slug: "tailwind",
    name: "Tailwind CSS",
    category: "styling",
    aliases: ["Tailwind", "TailwindCSS"],
    effort: 1,
    resources: doc("Tailwind CSS docs", "https://tailwindcss.com/docs"),
  },
  {
    slug: "sass",
    name: "Sass",
    category: "styling",
    aliases: ["SCSS", "Sass/SCSS"],
    effort: 1,
    resources: doc("Sass basics", "https://sass-lang.com/guide/"),
  },
  { slug: "css-modules", name: "CSS Modules", category: "styling", effort: 1 },
  {
    slug: "styled-components",
    name: "styled-components",
    category: "styling",
    aliases: ["Styled Components", "CSS-in-JS"],
    effort: 1,
  },
  { slug: "emotion", name: "Emotion", category: "styling", effort: 1 },
  { slug: "material-ui", name: "Material UI", category: "styling", aliases: ["MUI", "Material-UI"], effort: 1 },
  { slug: "chakra-ui", name: "Chakra UI", category: "styling", effort: 1 },
  { slug: "ant-design", name: "Ant Design", category: "styling", aliases: ["AntD"], effort: 1 },
  { slug: "bootstrap", name: "Bootstrap", category: "styling", effort: 1 },
  { slug: "shadcn-ui", name: "shadcn/ui", category: "styling", aliases: ["shadcn"], effort: 1 },
  { slug: "radix-ui", name: "Radix UI", category: "styling", effort: 1 },

  // Mobile
  {
    slug: "react-native",
    name: "React Native",
    category: "mobile",
    aliases: ["RN"],
    effort: 2,
    resources: doc("React Native docs", "https://reactnative.dev/docs/getting-started"),
  },
  { slug: "expo", name: "Expo", category: "mobile", effort: 1 },
  {
    slug: "flutter",
    name: "Flutter",
    category: "mobile",
    effort: 2,
    resources: doc("Flutter: get started", "https://docs.flutter.dev/get-started"),
  },
  { slug: "android", name: "Android", category: "mobile", aliases: ["Android SDK"], effort: 3 },
  { slug: "ios", name: "iOS", category: "mobile", aliases: ["iOS development", "SwiftUI"], effort: 3 },

  // Backend
  {
    slug: "nodejs",
    name: "Node.js",
    category: "backend",
    aliases: ["Node", "NodeJS", "Node JS"],
    effort: 2,
    resources: doc("Learn Node.js", "https://nodejs.org/en/learn"),
  },
  {
    slug: "express",
    name: "Express",
    category: "backend",
    aliases: ["Express.js", "ExpressJS"],
    effort: 1,
    resources: doc("Express guide", "https://expressjs.com/en/guide/routing.html"),
  },
  { slug: "nestjs", name: "NestJS", category: "backend", aliases: ["Nest.js", "Nest"], effort: 2 },
  { slug: "fastify", name: "Fastify", category: "backend", effort: 1 },
  { slug: "django", name: "Django", category: "backend", effort: 2 },
  { slug: "flask", name: "Flask", category: "backend", effort: 1 },
  { slug: "fastapi", name: "FastAPI", category: "backend", effort: 1 },
  { slug: "spring-boot", name: "Spring Boot", category: "backend", aliases: ["Spring"], effort: 3 },
  { slug: "dotnet", name: "ASP.NET Core", category: "backend", aliases: [".NET", ".NET Core", "ASP.NET"], effort: 3 },
  { slug: "laravel", name: "Laravel", category: "backend", effort: 2 },
  { slug: "rails", name: "Ruby on Rails", category: "backend", aliases: ["Rails", "RoR"], effort: 2 },
  {
    slug: "graphql",
    name: "GraphQL",
    category: "backend",
    aliases: ["Apollo GraphQL", "Apollo Client"],
    effort: 2,
    resources: doc("Learn GraphQL", "https://graphql.org/learn/"),
  },
  {
    slug: "rest-apis",
    name: "REST APIs",
    category: "backend",
    aliases: ["REST", "RESTful APIs", "RESTful", "REST API", "API integration"],
    effort: 1,
  },
  { slug: "trpc", name: "tRPC", category: "backend", effort: 1 },
  { slug: "grpc", name: "gRPC", category: "backend", effort: 2 },
  {
    slug: "websockets",
    name: "WebSockets",
    category: "backend",
    aliases: ["WebSocket", "Socket.IO", "SocketIO"],
    effort: 1,
  },
  {
    slug: "microservices",
    name: "Microservices",
    category: "backend",
    aliases: ["Microservice architecture"],
    effort: 3,
  },

  // Databases and data access
  {
    slug: "postgresql",
    name: "PostgreSQL",
    category: "database",
    aliases: ["Postgres", "psql"],
    effort: 2,
    resources: doc("PostgreSQL tutorial", "https://www.postgresql.org/docs/current/tutorial.html"),
  },
  { slug: "mysql", name: "MySQL", category: "database", effort: 2 },
  {
    slug: "mongodb",
    name: "MongoDB",
    category: "database",
    aliases: ["Mongo"],
    effort: 2,
    resources: doc("MongoDB University", "https://learn.mongodb.com/"),
  },
  { slug: "redis", name: "Redis", category: "database", effort: 1 },
  { slug: "sqlite", name: "SQLite", category: "database", effort: 1 },
  { slug: "firebase", name: "Firebase", category: "database", aliases: ["Firestore", "Firebase Auth"], effort: 1 },
  { slug: "supabase", name: "Supabase", category: "database", effort: 1 },
  { slug: "dynamodb", name: "DynamoDB", category: "database", effort: 2 },
  { slug: "elasticsearch", name: "Elasticsearch", category: "database", aliases: ["Elastic", "OpenSearch"], effort: 2 },
  {
    slug: "prisma",
    name: "Prisma",
    category: "database",
    aliases: ["Prisma ORM"],
    effort: 1,
    resources: doc("Prisma docs", "https://www.prisma.io/docs"),
  },
  { slug: "sequelize", name: "Sequelize", category: "database", effort: 1 },
  { slug: "typeorm", name: "TypeORM", category: "database", effort: 1 },
  { slug: "mongoose", name: "Mongoose", category: "database", effort: 1 },

  // Testing
  {
    slug: "jest",
    name: "Jest",
    category: "testing",
    effort: 1,
    resources: doc("Jest: getting started", "https://jestjs.io/docs/getting-started"),
  },
  {
    slug: "vitest",
    name: "Vitest",
    category: "testing",
    effort: 1,
    resources: doc("Vitest guide", "https://vitest.dev/guide/"),
  },
  {
    slug: "react-testing-library",
    name: "React Testing Library",
    category: "testing",
    aliases: ["RTL", "Testing Library", "@testing-library/react"],
    effort: 1,
    resources: doc("Testing Library docs", "https://testing-library.com/docs/react-testing-library/intro/"),
  },
  {
    slug: "cypress",
    name: "Cypress",
    category: "testing",
    effort: 1,
    resources: doc("Cypress docs", "https://docs.cypress.io/"),
  },
  {
    slug: "playwright",
    name: "Playwright",
    category: "testing",
    effort: 1,
    resources: doc("Playwright: getting started", "https://playwright.dev/docs/intro"),
  },
  { slug: "selenium", name: "Selenium", category: "testing", aliases: ["Selenium WebDriver"], effort: 2 },
  { slug: "mocha", name: "Mocha", category: "testing", aliases: ["Chai"], effort: 1 },
  { slug: "unit-testing", name: "Unit testing", category: "testing", aliases: ["Unit tests"], effort: 2 },
  {
    slug: "e2e-testing",
    name: "End-to-end testing",
    category: "testing",
    aliases: ["E2E testing", "E2E tests", "End to end testing"],
    effort: 2,
  },
  { slug: "tdd", name: "Test-driven development", category: "testing", aliases: ["TDD"], effort: 2 },

  // Tooling
  {
    slug: "webpack",
    name: "Webpack",
    category: "tooling",
    effort: 2,
    resources: doc("Webpack concepts", "https://webpack.js.org/concepts/"),
  },
  {
    slug: "vite",
    name: "Vite",
    category: "tooling",
    aliases: ["ViteJS"],
    effort: 1,
    resources: doc("Vite guide", "https://vite.dev/guide/"),
  },
  { slug: "babel", name: "Babel", category: "tooling", effort: 1 },
  { slug: "eslint", name: "ESLint", category: "tooling", effort: 1 },
  { slug: "prettier", name: "Prettier", category: "tooling", effort: 1 },
  { slug: "npm", name: "npm", category: "tooling", aliases: ["Yarn", "pnpm"], effort: 1 },
  {
    slug: "monorepo",
    name: "Monorepos",
    category: "tooling",
    aliases: ["Turborepo", "Nx", "Lerna", "Monorepo"],
    effort: 2,
  },
  {
    slug: "git",
    name: "Git",
    category: "tooling",
    aliases: ["Version control"],
    effort: 1,
    resources: doc("Pro Git book", "https://git-scm.com/book/en/v2"),
  },
  { slug: "github", name: "GitHub", category: "tooling", effort: 1 },
  { slug: "gitlab", name: "GitLab", category: "tooling", effort: 1 },
  { slug: "jira", name: "Jira", category: "tooling", effort: 1 },
  {
    slug: "figma",
    name: "Figma",
    category: "tooling",
    effort: 1,
    resources: doc("Figma help center", "https://help.figma.com/"),
  },
  {
    slug: "storybook",
    name: "Storybook",
    category: "tooling",
    effort: 1,
    resources: doc("Storybook docs", "https://storybook.js.org/docs"),
  },
  { slug: "postman", name: "Postman", category: "tooling", effort: 1 },
  { slug: "chrome-devtools", name: "Chrome DevTools", category: "tooling", aliases: ["DevTools"], effort: 1 },

  // Cloud and DevOps
  {
    slug: "aws",
    name: "AWS",
    category: "cloud",
    aliases: ["Amazon Web Services", "AWS Lambda", "S3", "EC2", "CloudFront"],
    effort: 3,
    resources: doc("AWS: getting started", "https://aws.amazon.com/getting-started/"),
  },
  { slug: "azure", name: "Microsoft Azure", category: "cloud", aliases: ["Azure"], effort: 3 },
  { slug: "gcp", name: "Google Cloud", category: "cloud", aliases: ["GCP", "Google Cloud Platform"], effort: 3 },
  { slug: "vercel", name: "Vercel", category: "cloud", effort: 1 },
  { slug: "netlify", name: "Netlify", category: "cloud", effort: 1 },
  {
    slug: "docker",
    name: "Docker",
    category: "cloud",
    aliases: ["Containers", "Docker Compose"],
    effort: 2,
    resources: doc("Docker: get started", "https://docs.docker.com/get-started/"),
  },
  {
    slug: "kubernetes",
    name: "Kubernetes",
    category: "cloud",
    aliases: ["K8s"],
    effort: 3,
    resources: doc("Kubernetes basics", "https://kubernetes.io/docs/tutorials/kubernetes-basics/"),
  },
  {
    slug: "ci-cd",
    name: "CI/CD",
    category: "cloud",
    aliases: ["CI CD", "Continuous integration", "Continuous deployment"],
    effort: 2,
  },
  {
    slug: "github-actions",
    name: "GitHub Actions",
    category: "cloud",
    effort: 1,
    resources: doc("GitHub Actions docs", "https://docs.github.com/en/actions"),
  },
  { slug: "jenkins", name: "Jenkins", category: "cloud", effort: 2 },
  { slug: "terraform", name: "Terraform", category: "cloud", effort: 2 },
  { slug: "linux", name: "Linux", category: "cloud", aliases: ["Unix", "Bash", "Shell scripting"], effort: 2 },
  { slug: "nginx", name: "Nginx", category: "cloud", effort: 1 },

  // Practices and concepts
  {
    slug: "responsive-design",
    name: "Responsive design",
    category: "practice",
    aliases: ["Responsive web design", "Mobile-first design"],
    effort: 1,
  },
  {
    slug: "accessibility",
    name: "Web accessibility",
    category: "practice",
    aliases: ["Accessibility", "a11y", "WCAG", "ARIA"],
    effort: 2,
    resources: doc("web.dev: Learn Accessibility", "https://web.dev/learn/accessibility"),
  },
  {
    slug: "web-performance",
    name: "Web performance",
    category: "practice",
    aliases: ["Performance optimization", "Core Web Vitals", "Lighthouse"],
    effort: 2,
    resources: doc("web.dev: Learn Performance", "https://web.dev/learn/performance"),
  },
  {
    slug: "seo",
    name: "SEO",
    category: "practice",
    aliases: ["Search engine optimization"],
    effort: 1,
    resources: doc(
      "Google SEO starter guide",
      "https://developers.google.com/search/docs/fundamentals/seo-starter-guide",
    ),
  },
  {
    slug: "pwa",
    name: "Progressive Web Apps",
    category: "practice",
    aliases: ["PWA", "Service workers"],
    effort: 1,
    resources: doc("web.dev: Learn PWA", "https://web.dev/learn/pwa"),
  },
  {
    slug: "ssr",
    name: "Server-side rendering",
    category: "practice",
    aliases: ["SSR", "SSG", "Static site generation", "ISR"],
    effort: 2,
  },
  {
    slug: "micro-frontends",
    name: "Micro-frontends",
    category: "practice",
    aliases: ["Microfrontends", "Micro frontends", "Module Federation"],
    effort: 2,
  },
  {
    slug: "design-systems",
    name: "Design systems",
    category: "practice",
    aliases: ["Component library", "Design system"],
    effort: 2,
  },
  {
    slug: "cross-browser",
    name: "Cross-browser compatibility",
    category: "practice",
    aliases: ["Cross browser testing"],
    effort: 1,
  },
  { slug: "agile", name: "Agile / Scrum", category: "practice", aliases: ["Agile", "Scrum", "Kanban"], effort: 1 },
  { slug: "code-review", name: "Code review", category: "practice", aliases: ["Code reviews"], effort: 1 },
  {
    slug: "system-design",
    name: "System design",
    category: "practice",
    aliases: ["Frontend system design", "Software architecture"],
    effort: 3,
    resources: doc("System Design Primer", "https://github.com/donnemartin/system-design-primer"),
  },
  {
    slug: "dsa",
    name: "Data structures and algorithms",
    category: "practice",
    aliases: ["DSA", "Data structures", "Algorithms"],
    effort: 3,
  },
  { slug: "oop", name: "Object-oriented programming", category: "practice", aliases: ["OOP", "OOPS"], effort: 2 },
  { slug: "functional-programming", name: "Functional programming", category: "practice", aliases: ["FP"], effort: 2 },
  {
    slug: "web-security",
    name: "Web security",
    category: "practice",
    aliases: ["OWASP", "XSS", "CSRF", "Security"],
    effort: 2,
    resources: doc("OWASP Top 10", "https://owasp.org/www-project-top-ten/"),
  },
  {
    slug: "i18n",
    name: "Internationalization",
    category: "practice",
    aliases: ["i18n", "Localization", "l10n"],
    effort: 1,
  },
  {
    slug: "web-components",
    name: "Web Components",
    category: "practice",
    aliases: ["Custom elements", "Shadow DOM"],
    effort: 1,
  },
  {
    slug: "authentication",
    name: "Authentication",
    category: "practice",
    aliases: ["OAuth", "JWT", "SSO", "Auth"],
    effort: 2,
  },
  { slug: "state-management", name: "State management", category: "practice", effort: 2 },

  // Data and AI
  { slug: "machine-learning", name: "Machine learning", category: "data", aliases: ["ML"], effort: 3 },
  {
    slug: "llm-apis",
    name: "LLM APIs",
    category: "data",
    aliases: ["OpenAI API", "Generative AI", "GenAI", "LLM"],
    effort: 1,
  },
  { slug: "prompt-engineering", name: "Prompt engineering", category: "data", effort: 1 },
  { slug: "pandas", name: "Pandas", category: "data", effort: 1 },

  // Soft skills
  { slug: "communication", name: "Communication", category: "soft", aliases: ["Communication skills"], effort: 2 },
  { slug: "leadership", name: "Leadership", category: "soft", aliases: ["Team leadership", "Tech lead"], effort: 3 },
  { slug: "mentoring", name: "Mentoring", category: "soft", aliases: ["Mentorship"], effort: 2 },
  {
    slug: "stakeholder-management",
    name: "Stakeholder management",
    category: "soft",
    aliases: ["Client communication"],
    effort: 2,
  },
  { slug: "problem-solving", name: "Problem solving", category: "soft", effort: 2 },
  { slug: "teamwork", name: "Teamwork", category: "soft", aliases: ["Collaboration"], effort: 1 },
];

/** [from, to, type]: "implies" gives full credit, "related" partial credit (SPEC §12.2). */
export const SKILL_RELATIONS: [string, string, "implies" | "related"][] = [
  ["nextjs", "react", "implies"],
  ["remix", "react", "implies"],
  ["gatsby", "react", "implies"],
  ["react-native", "react", "implies"],
  ["expo", "react-native", "implies"],
  ["react", "javascript", "implies"],
  ["typescript", "javascript", "implies"],
  ["nodejs", "javascript", "implies"],
  ["express", "nodejs", "implies"],
  ["nestjs", "nodejs", "implies"],
  ["fastify", "nodejs", "implies"],
  ["nuxt", "vue", "implies"],
  ["sveltekit", "svelte", "implies"],
  ["angular", "typescript", "implies"],
  ["redux-toolkit", "redux", "implies"],
  ["tailwind", "css", "implies"],
  ["sass", "css", "implies"],
  ["css-modules", "css", "implies"],
  ["styled-components", "css", "implies"],
  ["emotion", "css", "implies"],
  ["nextjs", "ssr", "implies"],
  ["react-testing-library", "unit-testing", "implies"],
  ["jest", "unit-testing", "implies"],
  ["vitest", "unit-testing", "implies"],
  ["cypress", "e2e-testing", "implies"],
  ["playwright", "e2e-testing", "implies"],
  ["github-actions", "ci-cd", "implies"],
  ["postgresql", "sql", "implies"],
  ["mysql", "sql", "implies"],
  ["redux", "state-management", "implies"],
  ["zustand", "state-management", "implies"],
  ["mobx", "state-management", "implies"],
  ["redux", "zustand", "related"],
  ["redux", "mobx", "related"],
  ["zustand", "jotai", "related"],
  ["tanstack-query", "swr", "related"],
  ["jest", "vitest", "related"],
  ["cypress", "playwright", "related"],
  ["playwright", "selenium", "related"],
  ["material-ui", "chakra-ui", "related"],
  ["material-ui", "ant-design", "related"],
  ["postgresql", "mysql", "related"],
  ["aws", "gcp", "related"],
  ["aws", "azure", "related"],
  ["webpack", "vite", "related"],
  ["formik", "react-hook-form", "related"],
  ["react", "vue", "related"],
  ["flutter", "react-native", "related"],
];
